### ISSUE TITLE
Recursive groups for Service Principals

### ISSUE THREAD

**Issue by simongottschlag** [manicminer/hamilton#1]
Hi!

Just found this project looking through the azuread terraform provider. Great work!

I've been building a reverse proxy that allows normal users and service principals to connect to any Kubernetes API and one part of this is extracting the groups they are members of.

I'm using a pure http client to get all the groups for a service principal, but after looking at this SDK it should fit quite well here instead.

Do you have any thoughts on adding this functionality to this SDK?

This is how I am doing it right now: https://github.com/XenitAB/azad-kube-proxy/blob/main/pkg/azure/service_principal.go

**Comment by simongottschlag** [comment]
I'm willing to give it a try and contribute it if it's something you would like. I'm not really good at programming, but should be able to solve it with some guidance.

**Comment by simongottschlag** [comment]
After looking through the code it seems like we don't have it for users either.

To be clear, what I would like to add is the following:
- https://docs.microsoft.com/en-us/graph/api/serviceprincipal-list-transitivememberof?view=graph-rest-1.0&tabs=http
- https://docs.microsoft.com/en-us/graph/api/user-list-transitivememberof?view=graph-rest-1.0&tabs=http

I would gladly try and add these myself with your approval.

**Comment by manicminer** [comment]
Hi @simongottschlag, thanks for requesting! I won't have time to add this for a week or two, but in the meantime I'm more than happy to accept contributions. This would be a really useful feature.

The long term goal is to have as much API coverage as possible, particularly as it's doubtful at this point that the official Azure Go SDK will ever receive MS Graph support.

I added some auth & client tests this weekend which should make it easier to develop. Please shoot any questions if you choose to have a go, it would be great to hear any feedback. Thanks!

**Comment by simongottschlag** [comment]
@manicminer I've created a first pull request for the user client: https://github.com/manicminer/hamilton/pull/5

**Comment by simongottschlag** [comment]
Thank you for the great work and quick response @manicminer ! :1st_place_medal:

**Comment by manicminer** [comment]
No worries, feel free to send along any other additions, or raise any bugs you find 👍

**Comment by simongottschlag** [comment]
@manicminer I was able to move over to your SDK in under an hour: https://github.com/XenitAB/azad-kube-proxy/pull/8

Thank you so much and I'll get back to you if I find any issues. Made my code much better using this! <3
