### ISSUE TITLE
Add support for `claimsMappingPolicy` 

### ISSUE THREAD

**Issue by tiwood** [manicminer/hamilton#118]
To be able to manage application claims mappings with Terraform we need to be able to use the `claimsMappingPolicy` API in `hamilton`.

## References

* https://github.com/hashicorp/terraform-provider-azuread/issues/644
* https://docs.microsoft.com/en-us/graph/api/resources/claimsmappingpolicy?view=graph-rest-1.0
* https://docs.microsoft.com/en-us/graph/api/serviceprincipal-post-claimsmappingpolicies?view=graph-rest-1.0&tabs=http

**Comment by computeracer** [comment]
I was taking a look at implementing support for this, but how do you suggest handling the `definition` field of a potential claims mapping policy struct?

Looking at the properties of a definition as defined in https://docs.microsoft.com/en-us/graph/api/resources/claimsmappingpolicy?view=graph-rest-1.0#properties-of-a-claims-mapping-policy-definition there are complex JSON object types. Are there any examples in the current code base for implemented resources that are similar?

It seems like we would need to implement a custom unmarshal and marshal json functions as well as possibly declare custom types for each of the definition properties. A naive implementation could just treat definition as an array of strings, and we ensure json encoded content, but looking for ideas :smile: 

I am open to any input on implementation. Thank you!

**Comment by manicminer** [comment]
@computeracer In this case the policy is just sent as a string, so for a first pass I'd suggest typing this as a string. The client will have to handle building the policy, using whatever data types make sense for the use case. Similarly for unmarshaling, just treat it as a string and return the field as such. No need to validate it either, just let the API do the work.
