### ISSUE TITLE
Official Microsoft Graph Go SDK

### ISSUE THREAD

**Issue by baywet** [manicminer/hamilton#122]
Hello everyone 👋

Vincent here from the Microsoft Graph SDKs team. I'm reaching out to announce we're working on an official Go SDK, we haven't announced the community preview yet as there are still a number of things we need to work through, but I though I'd reach out to give you an opportunity to provide feedback before anybody else!

A few benefits from this new SDK:
- Fluent style APIs to all endpoints of the API
- Contains all the models of the API
- Is updated weekly to always be in sync with the API
- Supports [v1](https://github.com/microsoftgraph/msgraph-sdk-go) and [beta](https://github.com/microsoftgraph/msgraph-beta-sdk-go)
- Relies on [Azure identity](https://github.com/Azure/azure-sdk-for-go/tree/main/sdk/azidentity) to provide support for multiple authentication flows (you also can implement your own authentication provider)
- Provides middleware for Retry handling and Redirect handling (more to come)
- And many more features to come!

As with every pre-previews, we have a [list of known limitations](https://github.com/microsoftgraph/msgraph-sdk-go-core/issues/1) we're working through.

We'd love for you to pop by the [repos under our org](https://github.com/microsoftgraph/msgraph-sdk-go), give it a try, and give us feedback on your experience with this new SDK.

**Comment by manicminer** [comment]
Hi @baywet, thanks for opening this issue and letting us know about work being done on the official SDK. It's great to see that one is being released, however as this is not a feature request or a bug report, I'm going to close this issue for now so that we can concentrate on our open work items.

**Comment by kaovd** [comment]
@baywet Relieving to know you will be supporting both v1 and beta as this has been a bit of a concern of mine especially with how much critical stuff could be considered in beta :)
