### ISSUE TITLE
Method to anotate AAD tier/service required for specific objects?

### ISSUE THREAD

**Issue by webframp** [manicminer/hamilton#146]
This is a really great library that was pretty easy to figure out from the logical structure of the code so far, nice work!

The testing section of the readme mentions this:

> some tests require an Azure AD Premium P2 license and/or an Office 365 license. You can authenticate with any supported method for the client tests, and the auth tests are split by authentication method.

In principle I hate the idea of any kind of selective behavior for test execution, but given the pricing structure of Azure services it seems unavoidable unless every potential contributor is willing to spend $$ for the requires SKUs to support executing all tests in their own local dev environment.

For some development use cases having an entire P2 AAD and O365 environment enabled to run tests seems like overkill. Do you have any ideas or suggestions how we could selectively disable parts of the test infrastructure that depend on those more expensive features?

**Comment by manicminer** [comment]
Hi @webframp, thanks for the kind words!

At this time I don't think it's very feasible to manually annotate fields and features based on pricing - not only would it be quite some effort but it would also have to keep up with regular service changes to be useful.

I would recommend signing up to the [Microsoft 365 Developer Program](https://developer.microsoft.com/en-us/microsoft-365/dev-program), as this offers a fully featured M365 E5 subscription (which includes AAD P2) for 25 users, for free for development purposes. This isn't mentioned anywhere in the project but I'll add it to the readme.

**Comment by webframp** [comment]
That's a great idea. Are you open to me adding some version of that info to the readme?

**Comment by manicminer** [comment]
In my haste I added a note to the readme already, but suggestions are very welcome if there's anything you feel would be good to add :)

**Comment by webframp** [comment]
Nope that looks good enough for me, I learned something new today!
