### ISSUE TITLE
DirectoryObject and similar collection types

### ISSUE THREAD

**Issue by webframp** [manicminer/hamilton#149]
I'm still learning a bit how everything in here is wired up, sorry if this is a beginner question. I was wondering if you could briefly explain how this is used to build the odata id url refs? Where does Uri method bound to this type get called?

```go
type DirectoryObject struct {
	ODataId   *odata.Id   `json:"@odata.id,omitempty"`
	ODataType *odata.Type `json:"@odata.type,omitempty"`
	ID        *string     `json:"id,omitempty"`
}

func (o *DirectoryObject) Uri(endpoint environments.ApiEndpoint, apiVersion ApiVersion) string {
	if o.ID == nil {
		return ""
	}
	return fmt.Sprintf("%s/%s/directoryObjects/%s", endpoint, apiVersion, *o.ID)
}
```

Thanks!

**Comment by manicminer** [comment]
Hi @webframp, at the moment that method isn't called anywhere, for now it's there as a convenience that you can call as needed from your app.

We used to look up odata IDs via the API, but unfortunately that no longer works. I'm hoping we can improve the handling of base API models like directoryObject and have things like the odata ID handled implicitly, but for now you'd have to explicitly construct these URIs where needed.

Hope this helps!

**Comment by webframp** [comment]
Exactly what I needed to know, thanks! I was guessing it wasn't called anywhere but wanted to confirm to make sure I wasn't missing something.
