### ISSUE TITLE
Support for Azure's management APIs

### ISSUE THREAD

**Issue by rnickmccandless** [manicminer/hamilton#164]
Are there any plans on your roadmap to add support for the endpoints of Azure's management APIs? 

This would apply to the existing endpoint constant already in [`ResourceManagerPublicEndpoint ApiEndpoint = "https://management.azure.com"`](https://github.com/manicminer/hamilton/blob/main/environments/endpoints.go#L24)

We're specifically looking for the ability to [list all custom subscriber roles definition list with a {scope}](https://docs.microsoft.com/en-us/azure/role-based-access-control/custom-roles-rest#list-custom-roles-at-a-scope) and potentially additional management endpoints in the future. 

~ Thank you

**Comment by manicminer** [comment]
Hi @rnickmccandless, thanks for the question! At this time we are not planning any API support outside of MS Graph and the authentication endpoints. This _might_ change in terms of data plane APIs specifically for Azure Active Directory or Microsoft 365 services, but the Service Management API is definitely out of scope as there are existing viable SDKs.

In the meantime I would encourage you to look at the [Azure SDK for Go](https://github.com/Azure/azure-sdk-for-go).
