### ISSUE TITLE
Support OIDC Authentication for Service Principals

### ISSUE THREAD

**Issue by ekristen** [manicminer/hamilton#165]
It would be nice to have OIDC authentication support instead of just GitHub Tokens, which appears to be a more specific unique implementation only to GitHub that differs from Kubernetes and the "Other Issuer" for OIDC support for Service Principal Authentication

**Comment by simongottschlag** [comment]
Hi @ekristen! 

GitHub is just a wrapper on top of Client Credentials. You can implement OIDC using it, having GitHub as a reference.

(I'm not the maintainer for Hamilton)

**Comment by ekristen** [comment]
I'm looking at contributing and I agree, the main reason for opening this is that it's being use in conjunction with Terraform Azure RM and that just gained "OIDC" support except it's not really OIDC, it's the GitHub Wrapped OIDC which means you can't actually use OIDC with it. 

Currently I'm using OIDC with Hamilton, but I have to write my own, then wrap it in autorest and then wrap it in Hamilton's autorest then reference it.

**Comment by tombuildsstuff** [comment]
@ekristen whilst OIDC from other providers _should_ work using the exposed fields (token & URI) - they're untested and unfortunately aren't something we can (officially) support due to how implementations may differ across different OIDC providers - but they _should_ work providing they're compatible with GitHub OIDC.

**Comment by ekristen** [comment]
@tombuildsstuff a generic OIDC validator would be as simple as allowing someone to provide a JWT token.

Assuming we are on the same page, the GitHub OIDC here is and isn't OIDC. The GitHub implementation should be called GitHub Actions or GitHub Token authentication as the only way it works is by running in GitHub Actions.

It assumes the `idTokenRequestUrl` is a special endpoint that GitHub hosts and that `idTokenRequestToken` is basically a GitHub PAT.  It exchanges the PAT for a JWT that it then sends to Azure for auth.

If there was a Generic JWT method, GitHub could use it as well as anyone that wants to use a Generic OIDC or Kubernetes federated authentication that they've configured on the service principal.

I've detailed this out on the Azure RM Terraform Provider https://github.com/hashicorp/terraform-provider-azurerm/issues/16900 and https://github.com/hashicorp/terraform-provider-azurerm/issues/16901

**Comment by ekristen** [comment]
🤦 I re-read and re-looked at the code, you are saying `ClientCredentialsConfig` can be used to authenticate with federated authentication, so the real issue is with how Terraform Azure Provider is implementing this and not a missing feature here.

**Comment by ekristen** [comment]
Thanks for your time @tombuildsstuff @simongottschlag

**Comment by ekristen** [comment]
Correct, and I've ended up writing my own as a workaround, but it's an ugly hack. I set the JWT to the REQUEST_TOKEN and REQUEST_URL to my hack API that takes the authorization grabs the JWT and returns it in the format expected. While this works, it's not practical for most.
