### ISSUE TITLE
Support Additional Azure Environments

### ISSUE THREAD

**Issue by blheatwole** [manicminer/hamilton#169]
[EnvironmentFromString](https://github.com/manicminer/hamilton/blob/82c4c5a2f374f826d0c49b0a839bebbe5009d49c/environments/environments.go#L103) hardcodes a list of supported environments. The Hashicorp Terraform Provider for AzureRM makes use of EnvironmentFromString [here](https://github.com/hashicorp/terraform-provider-azurerm/blob/852010ec4bf8fcf32e00051138de124032f6022f/internal/clients/builder.go#L61)

Because the list is hardcoded, the terraform provider is useless for [Azure environments whose URLs cannot be publicly published](https://azure.microsoft.com/en-us/global-infrastructure/government/national-security/). Azure provides a method to discover the URLs for all the endpoints referenced in the Environment structure by using the metadata URL. [A sample implementation of using this URL is located here](https://github.com/Azure/go-autorest/blob/7dd32b67be4e6c9386b9ba7b1c44a51263f05270/autorest/azure/metadata_environment.go#L96)

Please add `EnvironmentFromMetadataUrl(url string) (Environment, error)` to support additional Azure environments and make hamilton more globally useful.

Thanks!

**Comment by manicminer** [comment]
Hi @blheatwole, thanks for requesting. We have actually previously implemented a function to look up the MS Graph URL from an ARM metadata service - however to my knowledge MS Graph endpoints are still not published this way, making it impossible for us to support private/custom clouds.

I'm happy to leave this issue open to track this, although it is blocked at present until someone can demonstrate that an MS Graph endpoint is being published in a custom cloud. Ideally, it should be published for all clouds.

**Comment by blheatwole** [comment]
Running `curl https://management.azure.com/metadata/endpoints?api-version=latest` returns the following JSON:
```
[
  {
    "portal": "https://portal.azure.com",
    "authentication": {
      "loginEndpoint": "https://login.microsoftonline.com/",
      "audiences": [
        "https://management.core.windows.net/",
        "https://management.azure.com/"
      ],
      "tenant": "common",
      "identityProvider": "AAD"
    },
    "media": "https://rest.media.azure.net",
    "graphAudience": "https://graph.windows.net/",
    "graph": "https://graph.windows.net/",
    "name": "AzureCloud",
    "suffixes": {
      "azureDataLakeStoreFileSystem": "azuredatalakestore.net",
      "acrLoginServer": "azurecr.io",
      "sqlServerHostname": "database.windows.net",
      "azureDataLakeAnalyticsCatalogAndJob": "azuredatalakeanalytics.net",
      "keyVaultDns": "vault.azure.net",
      "storage": "core.windows.net",
      "azureFrontDoorEndpointSuffix": "azurefd.net"
    },
    "batch": "https://batch.core.windows.net/",
    "resourceManager": "https://management.azure.com/",
    "vmImageAliasDoc": "https://raw.githubusercontent.com/Azure/azure-rest-api-specs/master/arm-compute/quickstart-templates/aliases.json",
    "activeDirectoryDataLake": "https://datalake.azure.net/",
    "sqlManagement": "https://management.core.windows.net:8443/",
    "gallery": "https://gallery.azure.com/"
  },
  {
    "portal": "https://portal.azure.cn",
    "authentication": {
      "loginEndpoint": "https://login.chinacloudapi.cn",
      "audiences": [
        "https://management.core.chinacloudapi.cn",
        "https://management.chinacloudapi.cn"
      ],
      "tenant": "common",
      "identityProvider": "AAD"
    },
    "media": "https://rest.media.chinacloudapi.cn",
    "graphAudience": "https://graph.chinacloudapi.cn",
    "graph": "https://graph.chinacloudapi.cn",
    "name": "AzureChinaCloud",
    "suffixes": {
      "acrLoginServer": "azurecr.cn",
      "sqlServerHostname": "database.chinacloudapi.cn",
      "keyVaultDns": "vault.azure.cn",
      "storage": "core.chinacloudapi.cn",
      "azureFrontDoorEndpointSuffix": ""
    },
    "batch": "https://batch.chinacloudapi.cn",
    "resourceManager": "https://management.chinacloudapi.cn",
    "vmImageAliasDoc": "https://raw.githubusercontent.com/Azure/azure-rest-api-specs/master/arm-compute/quickstart-templates/aliases.json",
    "sqlManagement": "https://management.core.chinacloudapi.cn:8443",
    "gallery": "https://gallery.chinacloudapi.cn"
  },
  {
    "portal": "https://portal.azure.us",
    "authentication": {
      "loginEndpoint": "https://login.microsoftonline.us",
      "audiences": [
        "https://management.core.usgovcloudapi.net",
        "https://management.usgovcloudapi.net"
      ],
      "tenant": "common",
      "identityProvider": "AAD"
    },
    "media": "https://rest.media.usgovcloudapi.net",
    "graphAudience": "https://graph.windows.net",
    "graph": "https://graph.windows.net",
    "name": "AzureUSGovernment",
    "suffixes": {
      "acrLoginServer": "azurecr.us",
      "sqlServerHostname": "database.usgovcloudapi.net",
      "keyVaultDns": "vault.usgovcloudapi.net",
      "storage": "core.usgovcloudapi.net",
      "azureFrontDoorEndpointSuffix": ""
    },
    "batch": "https://batch.core.usgovcloudapi.net",
    "resourceManager": "https://management.usgovcloudapi.net",
    "vmImageAliasDoc": "https://raw.githubusercontent.com/Azure/azure-rest-api-specs/master/arm-compute/quickstart-templates/aliases.json",
    "sqlManagement": "https://management.core.usgovcloudapi.net:8443",
    "gallery": "https://gallery.usgovcloudapi.net"
  },
  {
    "portal": "https://portal.microsoftazure.de",
    "authentication": {
      "loginEndpoint": "https://login.microsoftonline.de",
      "audiences": [
        "https://management.core.cloudapi.de",
        "https://management.microsoftazure.de"
      ],
      "tenant": "common",
      "identityProvider": "AAD"
    },
    "media": "https://rest.media.cloudapi.de",
    "graphAudience": "https://graph.cloudapi.de",
    "graph": "https://graph.cloudapi.de",
    "name": "AzureGermanCloud",
    "suffixes": {
      "sqlServerHostname": "database.cloudapi.de",
      "keyVaultDns": "vault.microsoftazure.de",
      "storage": "core.cloudapi.de",
      "azureFrontDoorEndpointSuffix": ""
    },
    "batch": "https://batch.cloudapi.de",
    "resourceManager": "https://management.microsoftazure.de",
    "vmImageAliasDoc": "https://raw.githubusercontent.com/Azure/azure-rest-api-specs/master/arm-compute/quickstart-templates/aliases.json",
    "sqlManagement": "https://management.core.cloudapi.de:8443",
    "gallery": "https://gallery.cloudapi.de"
  }
]
```

Does the "graph" entry not have the correct endpoint? I note in some other environments that there is also a "microsoftGraphResourceId" field that contains the same URL as the "graph" field.

**Comment by manicminer** [comment]
Unfortunately all those "graph" endpoints are for the legacy [AAD Graph API](https://graph.windows.net) and not [Microsoft Graph](https://graph.microsoft.com). These are totally different API services.

**Comment by blheatwole** [comment]
Microsoft is working on updating the output of the `metadata/endpoints` api to include the Microsoft Graph endpoints. As soon as I get a sample of the new output, I will share that so that you can confirm whether it is useful to solve the issue.

**Comment by blheatwole** [comment]
I've gotten two different sample outputs. The first had a new key for Microsoft Graph:
```
{
  ...
  "graph": "https://graph.windows.net/",
  "microsoftGraphResourceId": "https://graph.microsoft.com/",
  ...
}
```

In the second, the 'graph' key was updated from AAD to Microsoft Graph
```
{
  ...
  "graph": "https://graph.microsoft.com/",
  ...
}
```

I'm not sure which of these they will eventually settle on. This update is currently planned to hit all clouds in less than two months, but that date could change.

At the point where they do release this, you should be able to discover the Microsoft Graph URL from the metadata endpoint. Does that give you what you need to provide a code-path for clouds whose URLs can't be publicly published?

**Comment by manicminer** [comment]
Thanks @blheatwole, it's good to know this is planned! Once this hits the major public clouds and/or we get confirmation this is stable in private clouds, we'll be able to support this fairly quickly and easily.

**Comment by blheatwole** [comment]
This change is currently being rolled out. Not all regions have it yet, but some do. You can test against this one already: https://eastus2euap.management.azure.com/metadata/endpoints?api-version=2022-09-01

Thanks!

**Comment by manicminer** [comment]
@blheatwole Great stuff, thanks for the headsup!

**Comment by manicminer** [comment]
@blheatwole Just checking in, perhaps you've heard some news on this?

**Comment by blheatwole** [comment]
MSFT says that the changes is applied to all regions

**Comment by manicminer** [comment]
I've been checking and this appears to be the case, thanks!
