### ISSUE TITLE
Struggling to get the msi authorizer to work

### ISSUE THREAD

**Issue by mathiaac** [manicminer/hamilton#177]
Hi, I'm having some issues with getting the msi authorizer to work. I'm kinda new to azure so might be something I'm not getting, but I'm getting this error when calling the groups client: 

GroupsClient.BaseClient.Get(): MsiAuthorizer: failed to request token from metadata endpoint: Get "http://169.254.169.254/metadata/identity/oauth2/token?api-version=2018-02-01&resource=https%3A%2F%2Fgraph.microsoft.com%2F": context deadline exceeded

This is how I set up the client and authorizer, am I missing something in the authConfig?

```
func NewClient(ctx context.Context, tenantID string) (*GraphClient, error) {
	environment := environments.Global

	authConfig := &auth.Config{
		EnableMsiAuth: true,
	}

	authorizer, err := authConfig.NewAuthorizer(ctx, environment.MsGraph)
	if err != nil {
		log.Fatal(err)
	}
	log.Println("Print authorizer token")
	log.Println(authorizer.Token())

	usersClient := msgraph.NewUsersClient(tenantID)
	groupsClient := msgraph.NewGroupsClient(tenantID)
	objectsClient := msgraph.NewDirectoryObjectsClient(tenantID)
	servicePrincipalClient := msgraph.NewServicePrincipalsClient(tenantID)
	usersClient.BaseClient.Authorizer = authorizer
	groupsClient.BaseClient.Authorizer = authorizer
	objectsClient.BaseClient.Authorizer = authorizer
	servicePrincipalClient.BaseClient.Authorizer = authorizer

	return &GraphClient{
		*groupsClient,
		*usersClient,
		*objectsClient,
		*servicePrincipalClient,
	}, nil
}
```

It is deployed to a Kubernetes pod, and it prints a token which I'm able to decode.

The error message stems from msi.go line 47, and based on the "context deadline exceeded" I was wondering if it was some timeout issue?

Anything that might point me to a solution is much appreciated!
Thanks in advance :)

**Comment by manicminer** [comment]
Hi @mathiaac, the message you are getting indicates the metadata service is not reachable from your pod. Since you are running in Kubernetes, I believe you will need to enable [workload identity](https://learn.microsoft.com/en-us/azure/aks/workload-identity-overview) / [pod identities](https://learn.microsoft.com/en-us/azure/aks/use-azure-ad-pod-identity).
