### ISSUE TITLE
Use of Resty client

### ISSUE THREAD

**Issue by yriveiro** [manicminer/hamilton#18]
First, nice work, very easy to understand, congrats

I have a question after reading your code, Did you think about the use [resty](https://github.com/go-resty/resty)? it's a small lib for REST that will handle backoff retries and you will be able to inject the oauth2 client.

Your code will get (even more) cleaner and easy to maintain probably.

**Comment by manicminer** [comment]
Thanks!

Rusty looks like a nice library, and with some features I'd definitely use, but a lot that I wouldn't. But mainly there are some things it doesn't do that are peculiar to MS Graph, such as unmarshaling error and generic odata attributes in responses. I confess I'm not entirely convinced the chained method approach to configuring a client is cleaner than struct population, but I guess that's a matter of taste. Given the base client is quite small in hamilton I don't feel the additional import brings enough extra benefit at the moment, although that might change in the future!

**Comment by yriveiro** [comment]
The `odata` stuff indeed needs to be handcrafted using a custom Unmarshal function like the `go-graph-sdk` does.

Regarding the chained method approach for configuration yes probably the programming language background will influence that.

Either way, the code is understandable and clean I will play a bit with it :)
