### ISSUE TITLE
Consider using beta version of API for accessPackage

### ISSUE THREAD

**Issue by stanleyz** [manicminer/hamilton#188]
The beta version returns more info than the v1.0 version, including the important `catalogId`, see below screenshots.

https://github.com/manicminer/hamilton/blob/74bfde92f0e8bc7ff08e94e45735f18baa3c80ee/msgraph/accesspackage.go#L20

<img width="1211" alt="Screen Shot 2022-10-07 at 10 36 27 PM" src="https://user-images.githubusercontent.com/1937584/194523587-a255b346-f0c4-426f-b9e8-b52ee6e354d2.png">

<img width="1245" alt="Screen Shot 2022-10-07 at 10 36 46 PM" src="https://user-images.githubusercontent.com/1937584/194523602-30306975-a84d-4a1a-b812-d82c09035529.png">

**Comment by manicminer** [comment]
@stanleyz THanks for the feature request. Whilst we typically default to v1.0 APIs, this can be overriden when using the SDK, for example:

```go
client = msgraph.NewAccessPackageClient(c.Connection.AuthConfig.TenantID)
client.BaseClient.ApiVersion = msgraph.VersionBeta
```

It's unlikely we'll change the default version, since it's possible for the user to override this whenever instantiating a client. Thanks!
