### ISSUE TITLE
Feature: Information about current identity

### ISSUE THREAD

**Issue by simongottschlag** [manicminer/hamilton#19]
Hi!

One thing I've been missing for a long time is to have "current user" information available easily.

Information that would be interesting:

- User Type (normal user or service principal / other?)
- Display Name
- AppID
- ObjectID

Not sure if this is actually possible, but a normal user does have information available from /me and I think some of the information should be available from the token. I know a service principal can lookup itself as long as it knows the AppID.

Thoughts? 😊

**Comment by manicminer** [comment]
One way this might be possible is by inspecting the claims in the access token and inferring some principal information from that. The populated claims do seem to be different when authorized as a service principal versus a user, but the SDK doesn't currently make any distinction as it doesn't need to.

Parsing the claims is already supported:
```go
token, _ := authorizer.Token()
claims, _ := auth.ParseClaims(token)
```

The `/me` endpoint is useful as you say, but only for users (I can't remember whether you get a 4xx or a dead response if you get that as an SP).

A service principal can request info about itself, either via it's corresponding application or directly:
```go
meMyself, _, _ := spClient.Get(ctx, claims.ObjectId)
```

Given the variety of possible scenarios, ultimately I think the logic here is going to be specific to your environment and it would be best to implement this in your application using some combination of the above. However if there are any missing pieces in the SDK it would be great to add those :)

**Comment by simongottschlag** [comment]
I fully agree! Thank you 🙏
