### ISSUE TITLE
Group writebackConfiguration

### ISSUE THREAD

**Issue by tomasmota** [manicminer/hamilton#196]
Hi, I have noticed that writebackConfiguration is not currently supported, is there a special reason for that? Is there another way to achieve that?

As far as I understand, all it requires is adding this to the group creation payload:
```
    "writebackConfiguration": {
        "isEnabled": true,
        "onPremisesGroupType":  UniversalSecurityGroup
    },
```

If there is no reason for this to not be there, I can make a PR for it

**Comment by manicminer** [comment]
Hi @tomasmota, thanks for raising this. PRs are welcome if you'd like to have a go at adding this :)
