### ISSUE TITLE
How to manage enterprise application service principal saml claims?

### ISSUE THREAD

**Issue by rgl** [manicminer/hamilton#224]
How can we manage a enterprise application service principal saml claims?

In the portal, these claims are managed at:

![image](https://user-images.githubusercontent.com/43356/219969997-8a3e391f-37e7-45b7-81ff-4291c3f49179.png)

![image](https://user-images.githubusercontent.com/43356/219970039-e37521cd-7e32-4466-80f6-a3ef374b6803.png)

![image](https://user-images.githubusercontent.com/43356/219970078-5355ee1d-e821-471f-8882-f791457f5cd6.png)

**Comment by rgl** [comment]
Ah, nice, since #147, @computeracer authored and @manicminer reviewed/committed the support for this. :-)

Do you guys known how to set an custom string valued attribute?

Using the following does not work at runtime, as the claim is not really set.

```json
{
  "ClaimsMappingPolicy": {
    "ClaimsSchema": [
      {
        "Source": "user",
        "ID": "\"Azure AD - QuickSight SSO\"",
        "JwtClaimType": "saml_subject",
        "SamlClaimType": "https://aws.amazon.com/SAML/Attributes/SAML_SUBJECT"
      }
    ]
```

**Comment by rgl** [comment]
I'm not able to understand how to create a transformed claim.

Can you please help?

I've tried this with terraform as:

```hcl
resource "azuread_claims_mapping_policy" "example" {
  display_name = azuread_application.example.display_name
  definition = [
    jsonencode(
      {
        ClaimsMappingPolicy = {
          Version              = 1
          IncludeBasicClaimSet = "true"
          ClaimsSchema = [
            {
              SamlClaimType    = "urn:example:transformation"
              Source           = "transformation"
              TransformationID = "join"
            },
          ]
          ClaimsTransformation = [
            {
              ID                   = "join"
              TransformationMethod = "Join" # TODO where is the complete documentation about this?
              InputParameters = [
                {
                  ID       = "string1"
                  Value    = "a" # TODO how to reference an existing claim? e.g. user.mail?
                },
                {
                  ID       = "string2"
                  Value    = "b"
                },
                {
                  ID       = "separator"
                  Value    = "-"
                }
              ]
              OutputClaims = [
                {
                  ClaimTypeReferenceId    = "mail" # TODO what value do we put here?
                  TransformationClaimType = "outputClaim"
                }
              ]
            }
          ]
        }
      }
    ),
  ]
}
```

But it fails with:

```
ClaimsMappingPolicy.BaseClient.Patch(): unexpected status 400 with OData error: Request_BadRequest: Property definition has an invalid value
```

How do we nest transformations and/or apply several transformations (e.g. Join -> Upper -> CreateClaim)?

Is there a reference to all the available transformations (examples would also be greatly appreciated)?

How is this related to https://learn.microsoft.com/en-us/azure/active-directory-b2c/claimstransformations? Is `ClaimsMappingPolicy` a JSON version of the b2c claimstransformations XML?
```

**Comment by kenchan0130** [comment]
@rgl 

I too had a hard time setting them up.
Your best bet is to look at HTTP requests on Azure Portal.

<img width="1035" alt="スクリーンショット 2023-03-03 0 24 06" src="https://user-images.githubusercontent.com/1155067/222471894-6f7948a6-522d-4a39-b711-e7c3f1ecf117.png">

This is a screenshot from Google Chrome DevTools.

I hope this helps you.

**Comment by rgl** [comment]
@kenchan0130, oh! thank you so much!

The portal UI data model even seems to match what is created by `azuread_claims_mapping_policy`. I hope they stay in sync in the future :-)
