### ISSUE TITLE
BUG: Create group does not chunk members/owners

### ISSUE THREAD

**Issue by Yanson** [manicminer/hamilton#47]
#### groups.go

As there is a limit of 20 link changes, `AddMembers` correctly splits the API calls into batches of 20. **However**, this logic is not followed when `Create` is called. This causes create group to fail when there is a combination of more than 20 owners + members.

Possible solution:

In `Create`, create the group with only owners (up to the first 20). Then use `AddOwners` to add the remaining owners and  `AddMembers` to add all the members. **Note:** The group must not be created without owners as it will leave the possibility of the authenticated client unable to modify the group if it does not have directory admin permissions.

**Comment by manicminer** [comment]
Thanks for raising this issue @Yanson. I agree that it would be nice to wrap this complexity in the Create method so the calling client does not have to worry about chunking the members/owners when creating a group. I do think there may be some hidden gotchas to this though - mainly with owners.

If we did this (handled >20 owners by creating the group with the first 20 owners, and then calling AddOwners for the remainder) it's possible that the group may get created with a set of owners that doesn't include the caller - thus effectively orphaning the group? There's also the potential for AddMembers or AddOwners to return an error, leaving the group partially created and more of a mess for the calling application to figure out.

So on balance, I'm not sure this would be worth it. Particularly when the workaround is fairly trivial - if >20 members/owners, create the group with the first 20, ensuring the most important owner(s) are included, then add the rest.

**Comment by Yanson** [comment]
Thank you for your reply.

> it's possible that the group may get created with a set of owners that doesn't include the caller - thus effectively orphaning the group

Yes, that's possible. The solution I proposed went for a balance between simplicity and capturing all edge-cases. I find it unlikely more than 20 owners would be listed. I expect either none (user is directory admin) or 1 (self). In the event the caller is not in the first 20 owners, they could rectify the situation with any of the 20 owners that were added. If you wanted to take it a step further, you could select the currently authenticated user and put them in the first batch, or even fail if there are owners specified the current caller is not included (we actually do that in our fork of the terraform provider to prevent orphaning).

> leaving the group partially created

Yes, again, with multiple API calls you can end up with partial creation. Given the update method already handles chunking, you could end up with a partially _updated_ group today, so I don't see that as a valid argument. I'm not sure it there's any retry logic, but you could help mitigate it with that sort of approach.

As you say, the workaround is to create the group first, then add the remaining members. This is very troublesome for us as it causes a two-step apply in Terraform, and produces a configuration that cannot be reapplied from scratch.

Given creating a group with > 20 owners already fails today, a satisfactory compromise could be to create a group with all owners (fail if there are more than 20), then call AddMembers to handle chunking of members.

What do you think? That would have minimal changes and addresses your concerns of creating an orphaned group.

**Comment by manicminer** [comment]
I think this does need addressing in Terraform but the fix will likely go into the AzureAD provider, as this really is up to the implementing app to decide how they want to manage.

**Comment by manicminer** [comment]
@Yanson On further thought I still believe this is best left to the calling application as they are privy to more context and will have a better picture of what's being attempted. With that in mind, I'm PRing a fix to the AzureAD Terraform provider that should resolve this in all the cases I can think of right now - see https://github.com/hashicorp/terraform-provider-azuread/pull/454

**Comment by Yanson** [comment]
Thanks for supplying a Terraform provider fix - that solves our problem.

My expectation was that the fix would be here so there is consistency with the AddMembers method. As long as it's solved from a user-perspective, I don't suppose it matters how and so this issue can be closed.

Thanks again.

**Comment by manicminer** [comment]
@Yanson Thanks, I'll go ahead and close this :)
