### ISSUE TITLE
How best to support patching objects with Schema Extensions

### ISSUE THREAD

**Issue by MarkDordoy** [manicminer/hamilton#73]
This SDK supports creating schema extensions, however it does not yet support for example adding an extensions data to an allowed object, for example a user. 

Reading the [documentation/examples](https://docs.microsoft.com/en-us/graph/extensibility-schema-groups) it looks like we need to perform a patch call against the target object, however our update functions for users/groups etc requires a user/group object which has no concept of the schema extension (as in theory it could be anything). 

I'd like to extend the SDK to support these kind of updates, however i'm looking to get some opinions on the best way to achieve this. 

I can get myself around the problem by writing my own function that expects the schema extension i want to use, but i want to make this generic and add to the SDK. 

Im still new to writing go so i'll welcome the most simple options  :-)

**Comment by manicminer** [comment]
Capability merged in #81
